name: example

environment:
  sdk: ">=3.8.0 <4.0.0"

dependency_overrides:
  morphy_annotation:
    path: ../morphy_annotation

dependencies:
  meta: any
  morphy_annotation:
    path: ../morphy_annotation

dev_dependencies:
  morphy:
    path: ../morphy
  build_runner: ^2.4.6
  test: ^1.24.8
  json_serializable: ^6.10.0
  json_annotation: ^4.9.0

