name: example

environment:
  sdk: ">=3.8.0 <4.0.0"

dependency_overrides:
  morphy_annotation:
    path: ../morphy_annotation

dependencies:
  morphy_annotation:
    path: ../morphy_annotation

dev_dependencies:
  morphy:
    path: ../morphy
  build_runner:
  test: ^1.25.0
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0


