name: morphy
description: Provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 1.5.0
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=8.1.1 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  source_gen: ^4.2.0
  morphy_annotation:
    git:
      url: https://github.com/atreeon/morphy.git
      path: morphy_annotation
      ref: release/1.5.0
  dartx: ^1.2.0

dev_dependencies:
  test: ^1.30.0

#  morphy_annotation: ^1.4.2
#

#    path: ../morphy_annotation
#  morphy_annotation:
#    git:
#      url: https://github.com/atreeon/morphy.git
#      ref: toString2
#      path: morphy_annotation

#dependency_overrides:
#  morphy_annotation:
#    path: ../morphy_annotation
