name: morphy_annotation
description: annotation for morphy which provides a clean class definition with extra functionality including; copy with, json serializable, tostring, equals that supports inheritance and polymorphism
version: 1.4.2
homepage: https://github.com/atreeon/morphy

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  collection: ^1.18.0
  dartx: ^1.2.0
  json_annotation: ^4.7.0
  quiver: ^3.0.1



